INSERT INTO PERSON_CONTACT_TYPE (ID) VALUES ('EMAIL');
INSERT INTO PERSON_CONTACT_TYPE (ID) VALUES ('PHONE');

INSERT INTO PERSON_CONTACT_STATE (ID) VALUES ('WAITED');
INSERT INTO PERSON_CONTACT_STATE (ID) VALUES ('CONFIRMED');
INSERT INTO PERSON_CONTACT_STATE (ID) VALUES ('REMOVED');

INSERT INTO OPERATION_STATE (ID) VALUES ('INITED');

INSERT INTO OPERATION_TYPE (ID) VALUES ('FLAT_RENTING');

INSERT INTO OPERATION_ROLE (ID) VALUES ('PAYER');
INSERT INTO OPERATION_ROLE (ID) VALUES ('MEDIATOR');
INSERT INTO OPERATION_ROLE (ID) VALUES ('CLAIMANT');

INSERT INTO OPERATION_PARTICIPANT_STATE (ID) VALUES ('WAITED');
INSERT INTO OPERATION_PARTICIPANT_STATE (ID) VALUES ('CONFIRMED');
